### ISSUE TITLE
Use field kinds within tree_map

### ISSUE THREAD

**Issue by thomaspinder** [cgarciae/treeo#2]
Firstly, thanks for creating Treeo - it's a fantastic package.

Is there a way to use methods defined within a field's `kind` object within a `tree_map` call? For example, consider the following MWE
```
import jax.numpy as jnp

class Parameter:
    def transform(self):
        return jnp.exp(self)


@dataclass
class Model(to.Tree):
    lengthscale: jnp.array = to.field(
        default=jnp.array([1.0]), node=True, kind=Parameter
    )
```

is there a way that I could do something similar to the following pseudocode snippet:
```
m = Model()
jax.tree_map(lamdba x: x.transform(), to.filter(m, Parameter))
```

**Comment by thomaspinder** [comment]
Hey @cgarciae , thanks, but perhaps my MWE was an oversimplification. The reason for defining the transform as a method of the kind class is that there can be numerous classes e.g.,
```
class PositiveParameter():
    def transform(self):
        return jnp.abs(self)

class NegativeParameter():
    def transform(self):
        return jnp.array(-1.) * self 
```
and so on...

This makes the solution you've proposed a little more tricky as there'd need to be some awkward function mappings.

**Comment by cgarciae** [comment]
@thomaspinder sure! That solution based on #3 works. For ergonomics you can convert `transform` to be a `staticmethod`.

**Comment by thomaspinder** [comment]
Sure! I'd be happy to contribute. Are you able to outline the main steps that I should be mindful of when doing this?

**Comment by cgarciae** [comment]
I think adding a `field_info: bool` argument to `map` and then conditionally using the `add_field_info` context manager over this line should be enough:

https://github.com/cgarciae/treeo/blob/master/treeo/api.py#L197

Also try to add a test :smiley:. Sadly we don't have a contributing document yet but to start developing do the following:

1. Install `poetry`
2. Run `poetry install` to install dependencies
3. Run `poetry shell` to activate environment.
4. Run `pre-commit install` to install precommit hooks.
5. Run `pytest` to run tests.
